[versions]
gradle = "8.5.2"
kotlin = "1.7.10"
[libraries]
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
kotlin-stdlib-jdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
[bundles]
[plugins]